### ISSUE TITLE
This app is still in development mode

### ISSUE THREAD

**Issue by MasterDaveh** [patw0929/react-native-cognito-login-example#1]
Hello, I tried building and running your app and all went fine, until I tried to login with Facebook. Below is the error message displayed. If it can help I logged in with Google fine.
<img width="429" alt="app in development mode" src="https://user-images.githubusercontent.com/16387187/32209790-6fda9e42-be0a-11e7-9391-0ca6dd70cb6b.png">

I'm not providing all my environment infos since this looks like an API issue, but if necessary I can provide them :)

**Comment by patw0929** [comment]
Did you use my original facebook application id in setting?
If yes, it is the expected result. Because my facebook application for this test is in dev mode, not published.

**Comment by MasterDaveh** [comment]
Oh ok, perfect! Didn't think about that, thanks :)

**Comment by MasterDaveh** [comment]
Hey @patw0929 I changed the identity pool id in the code but I'm still getting the error. Did you explicitly set a facebook app id somewhere? because I couldn't find it

**Comment by MasterDaveh** [comment]
I created a new Identity Pool on Cognito, enabled authentication with Facebook, provided my new app ID but the error is still showing up. I have also tried to set the FB app to public in the FB dashboard, but that didn't work also.

**Comment by MasterDaveh** [comment]
Never mind, I just found the App ID in the info.plist file
